### ISSUE TITLE
Add a played game to a list

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#1]
## Value proposition

**As a** user
**I need** to make a list of games I have played
**to be able** to remember them.

## Description
<img src="https://user-images.githubusercontent.com/67676597/156724720-f7b81c30-46a4-44a3-8028-a669fb4fa15d.png" width="400">

## Acceptance Criteria

- [x] The name of the game can be entered and will be displayed in the list after clicking the button.
- [x] If no games are entered yet, a placeholder text is displayed.
- [x] An empty form cannot be submitted
- [x] The list of the tracked Games should be scrollable
- [x] after submitting the form the input field is cleared
- [x] New entries are entered at the first position of the list

## Tasks

- [x] Create component TrackGameForm use Storybook and Styled-components
- [x]  Create component TrackedGamesList use Storybook and Styled-components
- [x]  Write Test for TrackGameForm
- [x]  Write Test for TrackedGamesList
- [x] Add to App
- [x] Check accessibility
