### ISSUE TITLE
Delete a tracked Game

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#16]
**As a** user
**I need** to delete a tracked game
**to be able to** remove incorrect entries.

## Description
<img src="https://user-images.githubusercontent.com/67676597/157843153-97b71632-3fc5-4ec3-a4fa-2722aa79453b.png" width="450">

## Acceptance Criteria

- [x] The games in the list have a delete button
- [x] When a user clicks on the delete button, a window appears asking the user for confirmation. If the delete request is not confirmed, the entry remains in the list and message appears.
- [x] When the deletion request is confirmed, a success message appears.

## Tasks

- [x] Check accessebility 
- [x] Check on mobile
- [x] Test the listing of games for the delete button
- [x] Build delete button in stroybook
