### ISSUE TITLE
Notes on one game

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#17]
**As a** user
**I need** to take notes on a game
**to be able to** remember which strategy I tried last time.

## Description
<img src="https://user-images.githubusercontent.com/67676597/159118187-11fdc3c3-dbca-4fdd-b3e5-2180e51d49b7.png" width="800"/>

## Acceptance Criteria
- [x] The textarea is not required
- [x] The textarea is displayed as the third step in the form.
- [x] The own notes are displayed with the details of a match.
- [x] The Dots are clickable

## Tasks

- [x] Add a third step to the form
- [x] Add Framer Motion
- [x] Adapt the form component test
- [x] Create the textarea in Storybook
- [x] Check accessebility
- [x] Check on mobile
- [x] Update README
