### ISSUE TITLE
Add personal score

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#2]
## Value proposition

**As a** user
**I need**
**to be able to** add my personal score

## Description
<img src="https://user-images.githubusercontent.com/67676597/156594836-19fa2cc1-d09c-4d7f-b987-9349de57d0bd.png" width="200">

## Acceptance Criteria

- [ ] After submitting the form, all input fields will be cleared. 
- [ ] The results of a game are displayed below the game name. 
- [ ] Each game result is a separate list entry.

## Tasks

- [ ] Extension of the TrackedGamesList component
- [ ] Extension of the TrackGameForm component
- [ ] Supplementation of the existing unit tests
