### ISSUE TITLE
Click on the game entry to see more details

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#20]
**As a** user
**I need** to see more details when clicking on the game entry
**to be able to** have a better overview of the games in the list.

## Description

<img src="https://user-images.githubusercontent.com/67676597/157847820-abc21fe2-2b91-4178-a4a3-7d39a46062be.png" width="400">

## Acceptance Criteria

- [ ] When closed, only the name of the game and the winner are displayed.
- [ ] In the expanded state, all players and results as well as the delete button are displayed.
- [ ] Clicking on an expanded entry collapses the entry again.

## Tasks

- [ ] Check acessebility
- [ ] Check on mobile
- [ ] Add to the GamesList component
