### ISSUE TITLE
Splitting the form in two pages

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#21]
## Value proposition

**As a** user
**I need** to be guided through the input process
**to be able to**  keep track of my entries.

## Description
<img src="https://user-images.githubusercontent.com/67676597/157857057-233f65f3-cf33-49bb-85c8-ddfd1d824d2c.png" width="500">

## Acceptance Criteria

- [ ] The game name is entered on a separate page.
- [ ] The players and their scores will be entered on a separate page.
- [ ] Clicking on the back button deletes all entries made so far.
- [ ] After clicking on back, the focus is on the game name.

## Tasks

- [ ] useNavigate from react Router to connect the pages.
- [ ] write test for the new form component.
- [ ] Save the submitted data in one array of objects.
