### ISSUE TITLE
Refactor FormComponent

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#22]
## Value proposition

**As a** developer
**I need** to have clean code for my forms
**to be able to** maintain, test and understand the code more easily

## Acceptance Criteria

- [ ] Identify and reduce redundant code.
- [ ] Higher performance
- [ ] Improved validation
- [ ] Improved user notifications

## Tasks

- [ ] Use useFormsHook to reduce code.
- [ ] Add additional Validation

**Comment by Quaquaro** [comment]
```
const useFetch = (input, { auto, ...init }) => {
  const [result, setResult] = useState([null, null, true]);

  const fetcher = useCallback(
    (query, config) =>
      fetch(query, config)
        .then((res) => res.json())
        .then((data) => setResult([null, data, false]))
        .catch((err) => setResult([err, null, false])),
    [input, init]
  );

  useEffect(() => {
    if (auto) fetcher(input, init);
  }, []); // if you want to fetch data only once, do this.

  return [...result, fetcher];
  //fetcher(refetch) function or can be used for post api call
};
```

**Comment by Quaquaro** [comment]
**Inside the component**
```

const Users = () => {
  const [err, users, loading, refetch] = useFetch(`/api/users`, {auto:true});

  const onClick = () => refetch(...);

  return (
    <div>
      {users.map((user) => <User key={user.id} user={user} />)}
    </div>
  );
}

```

**Comment by Quaquaro** [comment]
```
const Home = React.lazy(() => import('./Home'));
const About = React.lazy(() => import('./About'));
function MyComponent() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <Route path="/home" component={Home} />
      <Route path="/about" component={About} />
    </Suspense>
  );
}
```

**Comment by Quaquaro** [comment]
```
const [state, setState] = useState({
  count: 0,
  name: "",
});

const onClick = () => {
  setTimeout(() => {
    setState((prevState) => ({
      ...prevState,
      name: "John",
      count: prevState.count + 1,
    }));
  }, 1000);
};

```

**Comment by Quaquaro** [comment]
```
const getPrimaryColor = ({ theme }) => theme.colors.primary;
const getDefaultColor = ({ theme }) => theme.colors.secondary;

const Button = styled.button`
  background-color: ${getPrimaryColor};
  color: ${getDefaultColor};
`;

```

**Comment by Quaquaro** [comment]
```
return (
  <>
    {list.map((item) => (
      <React.Fragment key={item.id}>
        <SomeComponent />
        <SomeAnotherComponent />
      </React.Fragment>
    ))}
  </>
);

```
