### ISSUE TITLE
Add progressbar to form

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#29]
**As a** user
**I need** to see how many input steps I have already completed.
**to be able to** have an overview of where I am in the form.

## Description

<img src="https://user-images.githubusercontent.com/67676597/159118519-20008c81-b1c3-4328-a8f6-2319031f11c8.png" width="350px" />

## Acceptance Criteria

- [x] A progress bar giving the user feedback on the input steps is displayed

## Tasks

- [x] Create progressbar in TrackGamePage
- [x] Check on mobile
- [x] Check accessibility 
- [x] Update README
