### ISSUE TITLE
Implement BoardgameAtlas API

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#31]
**As a** user
**I need** to get search suggestions when entering game names
**to be able to** type fewer letters and thus complete the entry more quickly.

## Description
<img src="https://user-images.githubusercontent.com/67676597/159172588-ac889995-e96b-4e34-9219-5c04b4807111.png" width="350" />

## Acceptance Criteria

- [x] When three letters are typed, the Boardgame Atlas API is searched for matching entries.
- [x] A selection list of search results is displayed.
- [x] When a list entry in the list is clicked, the match is transferred to the input field.
- [x] A loading animation is displayed while the search is running.
- [x] If nothing is found, nothing happens. The user can enter the name and continue typing.

## Tasks
- [x] Fetching data from Boardgame Atlas API 
  - [x] Using axios library or fetch() 
- [x] Creation of a loading animation
  - [x] Storybook  
- [x] Check accessibility
- [x] Trying to build a custom hook for fetching
- [x] Check on mobile
- [x] Update README

**Comment by Quaquaro** [comment]
https://github.com/Quaquaro/capstone-project/issues/22#issuecomment-1073307692

**Comment by Quaquaro** [comment]
https://github.com/Quaquaro/capstone-project/issues/22#issuecomment-1073307833
