### ISSUE TITLE
Extra page for inputs

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#4]
## Value proposition

**As a** user
**I need** to have the possibility to make my entries on a separate page 
**to be able to** have a better overview.

## Description
<img src="https://user-images.githubusercontent.com/67676597/156734804-0116b0c7-eb98-4f4b-afed-441dc9b32537.png" width="400">

## Acceptance Criteria

- [x] If you click on "Track Game" the form for entering the game will open.
- [x] Clicking on the X will take you back to the games listing.
- [x] When "Confirm" is clicked, the user's entries are accepted and the listing of games is displayed.

## Tasks

- [x] Create new page AddGameFormPage.
- [x] Add React Router.
- [x] Define route to AddGameFormPage.
 button. 
- [x] Check accessibility (aria-label for the x-button)

**Comment by Quaquaro** [comment]
Done
