### ISSUE TITLE
Show Image of the game in the games list

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#44]
**As a** user
**I need** to have small pictures displayed in the list of games
**to be able to** find games more quickly in the list.

## Description
<img src="https://user-images.githubusercontent.com/67676597/159174798-3682a742-fabc-4ad2-9c9d-b9ea23503837.png" width="200" />

## Acceptance Criteria

- [x] Matching images from the Boardgame Atlas API are displayed in the Games List.
- [x] After the input is completed, the system searches for a suitable image, if no image is found, a placeholder image is displayed.
- [x] Display a placeholder as long as the image is being searched for.

## Tasks

- [x] Check accessibility
- [x] Implement Cache to avoid unnecessary fetching
- [x] Executing a query for the images
- [x] Show check hook when input is valid
- [x] Show pink cross when input is invalid
- [x] Adaptation of the tests, the Gameslist component
- [x] Check on mobile
- [x] Update README
