### ISSUE TITLE
Add input fields for 4 players

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#5]
## Value proposition

**As a** user
**I need** to record the results of up to four players
**to be able to** remember them for the next game.

## Description
<img src="https://user-images.githubusercontent.com/67676597/156748005-5ccc2bd9-437a-43e7-80cf-012c54386f07.png" width="300">

## Acceptance Criteria

- [x] The results of the games have no influence on the sorting.
- [x] The player results are sorted according to the order in which they were entered. Player one is always first.
- [x] The following input fields must be filled in. The game name, the first player name and the result of the first player.

## Tasks

- [x] Extension of the AddGameForm component with 6 additional input fields.
- [x] Test whether the input fields of the additional players can be empty when submitting.
- [x] Check the new inputs accessibility
