### ISSUE TITLE
Add counter for the number of players.

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#6]
## Value proposition

**As a** user
**I need** to indicate the number of players I played with
**to be able to** display only the required input fields.

## Description
<img src="https://user-images.githubusercontent.com/67676597/157853798-85fb8de0-0499-4b85-bce0-bad2086f3e27.png" width="500">

## Acceptance Criteria

- [x] The default value is 2 players.
- [x] A maximum of 6 players and their results can be entered.
- [x] Clicking on the arrow takes me back to the name of the game.
- [x] When I click on back, I can edit the name of the game and change the number of players.
- [x] The +/- buttons can be used to reduce or increase the number of players. 
- [x] The counter can only be lowered to 1
- [x] Each player entered is displayed on the list of players in the game.

## Tasks

- [x] Passing the counter value to the function that renders the player inputs.
- [x] Check accessebility
- [x] Check on mobile
- [x] Write test for the counter.
- [x] Design + and - Button in Storybook.
- [x] Adapt the test of the FormComponents.
- [x] Make the PlayersForm Scrollable
