### ISSUE TITLE
Add local storage

### ISSUE THREAD

**Issue by Quaquaro** [Quaquaro/capstone-project#7]
## Value proposition

**As a** user
**I need** to have my tracked games list to be persisted between page loads
**to be able to**  keep them. 

## Description
<img src="https://user-images.githubusercontent.com/67676597/156757300-3fab8f99-51da-4b30-96a5-ed16842b7c4c.png" width="200">

## Acceptance Criteria

- [x] If no data is found in the local storage, a message is displayed for the user.
- [x] The tracked games list state is persisted between page loads.
- [x] Im Local Storage sollen folgende Daten gespeichert werden: Spielname und Spielername mit Ergebnis.

## Tasks

- [x] Implement local storage as custom hook (useLocalStorage)
- [x] Use conditional rendering to generate an output in the TrackedGamesList depending on the content of the local storage.
- [x] Save a array of objects in the local storage [{gameName: Munchkin, Player1: {name: Eric, score: 15}}]
